[[redirects]]
    from = "/api"
    to = "https://bibliothecamanagerapi.azurewebsites.net/swagger"

[[redirects]]
    from ="/v1/*"
    to = "https://bibliothecamanagerapi.azurewebsites.net/v1/"
    force = true
    headers = {Access-Control-Allow-Origin = "*"}