[[redirects]]
    from = "/api"
    to = "https://bibliothecamanagerapi.azurewebsites.net/swagger"

[[redirects]]
    from ="/v1/*"
    to = "https://bibliothecamanagerapi.azurewebsites.net/v1"

[[headers]]
  for = "/v1/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"