[[redirects]]
    from = "/api"
    to = "https://bibliothecamanagerapi.azurewebsites.net/swagger"

[[redirects]]
    from ="/v1/*"
    to = "https://bibliothecamanagerapi.azurewebsites.net/v1"
    force = true
    headers = {X-From = "Netlify"}
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"